('A_INSTRUCTION', '0', '@0\n', 0)
('C_INSTRUCTION', 'D', 'M', '', 'D=M\n', 1)
('A_INSTRUCTION', '23', '@23\n', 2)
('C_INSTRUCTION', '', 'D', 'JLE', 'D;JLE\n', 3)
('A_INSTRUCTION', '16', '@16\n', 4)
('C_INSTRUCTION', 'M', 'D', '', 'M=D\n', 5)
('A_INSTRUCTION', '16384', '@16384\n', 6)
('C_INSTRUCTION', 'D', 'A', '', 'D=A\n', 7)
('A_INSTRUCTION', '17', '@17\n', 8)
('C_INSTRUCTION', 'M', 'D', '', 'M=D\n', 9)
('A_INSTRUCTION', '17', '@17\n', 10)
('C_INSTRUCTION', 'A', 'M', '', 'A=M\n', 11)
('C_INSTRUCTION', 'M', '-1', '', 'M=-1\n', 12)
('A_INSTRUCTION', '17', '@17\n', 13)
('C_INSTRUCTION', 'D', 'M', '', 'D=M\n', 14)
('A_INSTRUCTION', '32', '@32\n', 15)
('C_INSTRUCTION', 'D', 'D+A', '', 'D=D+A\n', 16)
('A_INSTRUCTION', '17', '@17\n', 17)
('C_INSTRUCTION', 'M', 'D', '', 'M=D\n', 18)
('A_INSTRUCTION', '16', '@16\n', 19)
('C_INSTRUCTION', 'MD', 'M-1', '', 'MD=M-1\n', 20)
('A_INSTRUCTION', '10', '@10\n', 21)
('C_INSTRUCTION', '', 'D', 'JGT', 'D;JGT\n', 22)
('A_INSTRUCTION', '23', '@23\n', 23)
('C_INSTRUCTION', '', '0', 'JMP', '0;JMP\n', 24)
